# Docker Compose pour un environnement de développement

networks:
    my-apps-network:
        driver: bridge


services:
    nginx:
      image: nginx:latest
      container_name: nginx
      ports:
          - "80:80"
      restart: always
      volumes:
          - ./nginx_dev.conf:/etc/nginx/conf.d/default.conf
          - ./index.html:/usr/share/nginx/html/index.html
      networks:
          - my-apps-network
    
    proxy:
      container_name: proxy
      build:
          context: ../proxy
          target: 'development-stage'
      ports:
          - "5000"
      restart: always
      volumes:
          - ../proxy:/app
      networks:
          - my-apps-network

    movie-db-vue:
        container_name: movie-db-vue
        build:
            context: ../Movie_db_app/movie-db-vue
            target: 'development-stage'
        ports:
            - "8080:8080" # En développement, on expose le port 8080 mais pas en production
        restart: always
        volumes:
            - ../Movie_db_app/movie-db-vue:/app
        command: /bin/sh -c "npm install && quasar dev"
        networks:
            - my-apps-network

    movie-db-core-api:
        container_name: movie-db-core-api
        build:
            context: ../Movie_db_app/movie-db-core-api
            target: 'development-stage'
        ports:
            - "3000"
        restart: always
        volumes:
            - ../Movie_db_app/movie-db-core-api:/app
        networks:
            - my-apps-network
    
        