# Copy this file on the server at the same location as the docker-compose.yml file

resolver 127.0.0.11 valid=5s;

upstream portfolio_backend {
    zone portfolio_backend 64k;
    server sv-portfolio:8081 resolve;
}

upstream moviedb_api_backend {
    zone moviedb_api_backend 64k;
    server movie-db-core-api:3000 resolve;
}

upstream moviedb_vue_backend {
    zone moviedb_vue_backend 64k;
    server movie-db-vue:8080 resolve;
}

upstream airjewels_backend {
    zone airjewels_backend 64k;
    server airjewels-rails:3001 resolve;
}

upstream academint_backend {
    zone academint_backend 64k;
    server academint:3002 resolve;
}

upstream proxy_backend {
    zone proxy_backend 64k;
    server proxy:5000 resolve;
}

server {
    listen 80;
    listen [::]:80;
    server_name _;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name _;

    ssl_certificate /etc/ssl/cloudflare/cloudflare.crt;
    ssl_certificate_key /etc/ssl/cloudflare/cloudflare.key;

    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;

    location / {
        proxy_pass http://portfolio_backend;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /movie-db-app/api {
        proxy_pass http://moviedb_api_backend;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /movie-db-app/ {
        proxy_pass http://moviedb_vue_backend;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /airjewels-rails/ {
        proxy_pass http://airjewels_backend;
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Host $http_host;
    }

    location /academint/ {
        proxy_pass http://academint_backend;
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Host $http_host;
    }

    location /proxy {
        proxy_pass http://proxy_backend;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}