name: Deploy to Server

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Add server to known hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts

      - name: Copy files to server
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > private_key.pem
          chmod 600 private_key.pem
          scp -i private_key.pem ./docker-compose.raspberrypi.yml ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }}:Projets/my_apps/docker-compose.yml
          scp -i private_key.pem ./index.html ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }}:Projets/my_apps/index.html
          scp -i private_key.pem ./nginx.conf ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }}:Projets/my_apps/nginx.conf
          rm -f private_key.pem
